import { Router } from 'express';
import authRoutes from './auth.routes.js';
import projectRoutes from './project.routes.js';
import experienceRoutes from './experience.routes.js';
import serviceRoutes from './service.routes.js';
import skillRoutes from './skill.routes.js';
import testimonialRoutes from './testimonial.routes.js';
import contactRoutes from './contact.routes.js';
import donationRoutes from './donation.routes.js';
import blogRoutes from './blog.routes.js';
import settingsRoutes from './settings.routes.js';
import adminRoutes from './admin.routes.js';
import uploadRoutes from './upload.routes.js';
import analyticsRoutes from './analytics.routes.js';

const router = Router();
router.get('/health', (_req, res) => res.json({ success: true, message: 'OK', data: { uptime: process.uptime() } }));
router.use('/auth', authRoutes);
router.use('/uploads', uploadRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/projects', projectRoutes);
router.use('/experience', experienceRoutes);
router.use('/services', serviceRoutes);
router.use('/skills', skillRoutes);
router.use('/testimonials', testimonialRoutes);
router.use('/contact', contactRoutes);
router.use('/donations', donationRoutes);
router.use('/blog', blogRoutes);
router.use('/settings', settingsRoutes);
router.use('/admin', adminRoutes);
export default router;
